esphome:
  includes:
    - Messages.h
    - Patterns.h
    - Patterns.cpp

rp2040:
  board: rpipicow

preferences:
  flash_write_interval: 1min

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_ssid_backup
    password: !secret wifi_password

captive_portal:

web_server:

number:
  - platform: template
    name: "Output"
    id: output
    min_value: 0
    initial_value: 0
    max_value: 99
    step: 1
    optimistic: true
  - platform: template
    name: "Pattern"
    id: pattern
    min_value: 0
    initial_value: 0
    max_value: 99
    step: 1
    optimistic: true
    set_action:
      then:
        - rgb_led.run:
            id: patterngo
            red: !lambda 'return x;'
  - platform: template
    name: "Speed"
    id: speed
    min_value: 0
    initial_value: 0
    max_value: 99
    step: 1
    optimistic: true
  - platform: template
    name: "Repeat"
    id: repeat
    min_value: 0
    initial_value: 0
    max_value: 99
    step: 1
    optimistic: true
  - platform: template
    name: "Color"
    id: color
    min_value: 0
    initial_value: 1677215
    max_value: 1677215
    step: 1
    optimistic: true
  - platform: template
    name: "Brightness"
    id: brightness
    min_value: 0
    initial_value: 32
    max_value: 99
    step: 1
    optimistic: true